### install and import dependencies

In [ ]:
!pip install ultralytics
!pip install opencv-contrib-python

In [1]:
from ultralytics import YOLO
import cv2

### test trained yolov8 model on image

In [10]:
model = YOLO('best.pt')         #load your custom model

im0 = cv2.imread('tes.jpg')

results = model.predict(im0,
    conf=0.3,
    show=False,
    show_labels=True,
    classes=[0],
    stream=True
)

for result in results:
    boxes = result.boxes.cpu().numpy()
    class_name = 'subject'
    text = f'participant count: {len(boxes)}'
    cv2.putText(im0, text,(30,50),cv2.FONT_HERSHEY_SIMPLEX, 2, (200, 255, 255), 2)
    
    for box in boxes:                                          
        r = box.xyxy[0].astype(int)                            
        print(r)                                               
        cv2.rectangle(im0, r[:2], r[2:], (0, 0, 255), 2)
        cv2.putText(im0, class_name, (r[0], r[1] - 10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
    
    
cv2.imwrite("output_img.jpg", im0)


[1101  554 1607 1024]
[1173  318 1410  654]
[1033    1 1174  230]
[1115  108 1280  470]
[595 120 742 564]
0: 480x800 5 0s, 262.0ms
Speed: 4.0ms preprocess, 262.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 800)


True

### test on video

In [12]:
model = YOLO('best.pt')   ##load your custom model

cap = cv2.VideoCapture("tes3.avi")
assert cap.isOpened(), "Error reading video file"

video_writer = cv2.VideoWriter("output_vid.mp4",
                       cv2.VideoWriter_fourcc(*'mp4v'),
                       int(cap.get(5)),
                       (int(cap.get(3)), int(cap.get(4))))

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
        
    results = model.predict(im0,
    conf=0.3,
    show=False,
    show_labels=True,
    classes=[0],
    stream=True
)    
    for result in results:
        boxes = result.boxes.cpu().numpy()
        class_name = "subject"
        text = f'participant count: {len(boxes)}'
        cv2.putText(im0, text,(30,50),cv2.FONT_HERSHEY_DUPLEX, 2, (0, 0, 255), 2)
        for box in boxes:                                          
            r = box.xyxy[0].astype(int)                                                                           
            cv2.rectangle(im0, r[:2], r[2:], (0, 255, 0), 2)
            cv2.putText(im0, class_name, (r[0], r[1] - 10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 1)
        
    video_writer.write(im0)
        
cap.release()
video_writer.release()


0: 480x800 19 0s, 206.0ms
Speed: 4.0ms preprocess, 206.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 800)

0: 480x800 18 0s, 214.0ms
Speed: 3.0ms preprocess, 214.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 800)

0: 480x800 18 0s, 202.0ms
Speed: 4.0ms preprocess, 202.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 800)

0: 480x800 18 0s, 226.0ms
Speed: 4.0ms preprocess, 226.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 800)

0: 480x800 18 0s, 235.0ms
Speed: 7.0ms preprocess, 235.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 800)

0: 480x800 19 0s, 207.0ms
Speed: 4.0ms preprocess, 207.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 800)

0: 480x800 19 0s, 204.0ms
Speed: 3.0ms preprocess, 204.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 800)

0: 480x800 18 0s, 221.0ms
Speed: 4.0ms preprocess, 221.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 800)
